### ISSUE TITLE
Deliver `transcript.txt` to users

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1009]
Separated from #1004 Not of high priority, but urrently we have `.sos/transcript.txt` a hidden "feature". It is useful to me from time to time in debugging my code. However we might want to improve it (lock-protect, add step names) and formally present to users. Making it part of the report is not convenient because by default i do not generate reports: it takes a while to plot those DAGs.

**Comment by BoPeng** [comment]
For the report comment, it is easy to include it to reports, and it can be useful to let users know what exactly has been run. There are two caveats though:

1. Transcript is not available for remote tasks, and those are arguably the most interesting ones. I do feel a need to include trascripts in task files, because these reflects host-specific scripts and are very useful for debugging.

2. Transcript can be very long if we apply a script to thousands of files. A walkaround is to log only `__index=0`.

Transcripts are far less weight than DAG, and this is why DAG is only included with option `-d`.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/43908438-99e420fa-9bbd-11e8-9d3f-7edaa46d922e.png)

Transcript added to workflow report. At some place we might want to say that the transcripts are not complete transcripts of all scripts executed.
