### ISSUE TITLE
Lock error with concurrent and undetermined output.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1013]
The following code triggers an error:
```
input: for_each={'i': range(5)}, concurrent=True
output: dynamic('*.txt')
import random
sh: expand=True
touch {random.randint(0, 10000)}.txt
```

```
ERROR: [default]: Unrecognized file: False of type bool
```

**Comment by gaow** [comment]
Does it trigger lock error? I cannot reproduce with this code.

But I re-submitted a successfully completed job for my data analysis. Here are some observations:

1. signature check ("... is ignored due to saved signature") is slower now that all my `db` are about 40Mb in size. It is about 2 signatures per second. 

2. 30 out of my ~1500 tasks were resubmitted due to signature check failure. 

Both problems boil down to read/write of the sqlite database.

**Comment by gaow** [comment]
is [this implementation](https://github.com/RaRe-Technologies/sqlitedict/blob/master/sqlitedict.py#L366) relevant to what we need here? There is perhaps loss of performance but looks like safer to use a manager thread.

**Comment by BoPeng** [comment]
The signatures are now in an sqlite database in compressed state, so it is slower to read. This explains why your test on file signature is ok since step signatures can involved large variables and could be a lot slower to read/write. Yesterday's patch should help and the warning message should let us know which database has the problem.

**Comment by BoPeng** [comment]
The problem here is also from saved signature where `dynamic` result is not properly returned and processed. The problem here is that 

1. When the substeps are executed, the output is dynamic, so it has to get `*.txt` at the end, which can be generated by others. Hopefully these output can be saved to signatures.
2. When the step is re-executed, the signatures will be used, and should set `_output`.
3. The step should produce `step_output` from `_output` of substeps. These are not done properly when when substeps are executed concurrently.

I think I will try to address these issues in the local_sig branch along with other signature related issues.
