### ISSUE TITLE
task does not updated walltime

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1019]
Related to #1018 : one reason for the hang was walltime too short. I therefore changed walltime for one of my tasks from 40min to 80min, and reran the workflow. However, it still failed due to walltime problem. I checked `sos status ` with `-v4`. I see the walltime was not changed:

```
 'run_mode': 'run',
 'sig_mode': 'default',
 'verbosity': 2,
 'walltime': '00:40:00'}
```

But in my `task` statement I did already update walltime. It seems the old task was sbumitted without updating the configruations?

**Comment by BoPeng** [comment]
Yes, that is a bug. Fixing it.

**Comment by BoPeng** [comment]
The problem was that sos assumed the task body does not need to be updated when task id is the same, but the assumption is wrong because runtime info such as `walltime` is part of runtime info and does not contribute to task id.

This is actually a file format issue because the original assumption makes more sense and the fileformat should save runtime info separately... Anyway, a patch has been pushed and hopefully does not break other things.
