### ISSUE TITLE
Actions and file signature

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1065]
We used to use file and workflow signatures from actions. For example, `download` would save and check file signatures when the file already exists, and script running actions would save transcripts (scripts) to workflow database. However, with the introduction of zmq, these processes would need to know the address of the master sos process to be able to access signatures. This is not always possible because for example actions could be run from an external task without access to sos master.

Now if action `download` cannot check signature, I am not sure what the behavior would be for downloading files if the files already exist. We would not be able to continue downloading if we simply skip action `download` if file already exist, and we would be wasting time if we re-download everything. It is therefore recommended to use `tracked=True` to track the output of the `download` action, although this was done automatically before.

**Comment by gaow** [comment]
It sounds this is a compound question: action signature in general, and behavior of `download`.

For `download`, I assume for current implementation if `dest` is specified, we will not re-download if its signature is complete, and we'll re-download when `dest` is not specified? I think this is reasonable behavior? Now, if a download action with `dest` failed, due to #1055 we will remove the incomplete output, right? It looks like either we live with it, or we will have to do something specific to `download` action to counteract #1055.

>  It is therefore recommended to use tracked=True to track the output of the download action, although this was done automatically before.

Same as `dest`? why is it not automatically done now?

Now back to actions in general: not sure if I understand the problem. Dont we need to check signature for output files and action scripts anyways in order to determine rerun? Though I'm sure it is the case I did verify again with the `zmq` branch, by changing scripts for a workflow step and observing that it indeed triggered rerun. So from your description I'm not sure what issue we are dealing with for other actions ...

**Comment by BoPeng** [comment]
What I meant was that some actions can access signatures by themselves without the help from sos executor. In case of `download`, it saves file signature and ignores if existing file matches signature. With moving to zmq, it is more complicated to let actions access the signature database (but anything is possible) so we will have to do something like:

```
output: downloaded_files
download:
   urls
```
to let SoS handles signature, although it is sometimes difficult to know the name of output files in advance and there can be many download files.

**Comment by gaow** [comment]
I see. Could you be more specific about some actions: only `download` for now? And you use the generic word "some actions" because we want to use this opportunity to find a generic solution?

I think I now appreciate the challenge. Other than having users specifying it at step level, the quick and dirty solution is to have separate signature tracking system for `download`, or more generically `actions.db` ... just thinking aloud.

**Comment by BoPeng** [comment]
Right now just download. Actually with the merging of file signature to step signature the file signature is only used for this action (right now) and it makes senses to revert back to old file based signature for it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BoPeng** [comment]
It is because the action does not always have access to the controller.  I have been thinking about it and tend to think we should either use multithreading (one process) or use whet.  SoS does not have to care how many processes used by wget

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
