### ISSUE TITLE
Remove input options `filetype`

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1066]
[Input option `filetype`](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Step.html#Option-filetype) was carried over from the DPT time and is not useful with the more flexible design of SoS. 

The first example
```
!touch a.fastq b.fastq README.txt
%run
[step]
input: '*', filetype='*.fastq'
print(f"{input}")
```
is silly because users can do
```
!touch a.fastq b.fastq README.txt
%run
[step]
input: '*.fastq'
print(f"{input}")
```
although it meant to handle implicit input from previous step. 

The second example makes a bit more sense
```
%sandbox
!echo '##fileformat=VCF4.1' > a.vcf
!echo '#!/usr/bin/env python' > a.py
%run

[step]
input: '*', filetype=lambda x: open(x).readline().startswith('##fileformat=VCF4.1')
print(f"{_input}")
```
as it can be used to remove non-matching or empty input files, but the use of lambda function in an option named `filetype` is really ugly and intuitive, and the example can be written as

```
%sandbox
!echo '##fileformat=VCF4.1' > a.vcf
!echo '#!/usr/bin/env python' > a.py
%run

[step]
import glob
files = [open(x).readline().startswith('##fileformat=VCF4.1' for x in glob.glob('*')]

input: files
print(f"{_input}")
```
which is not much more code, and more flexible because more complex things can be done explicitly.

I would therefore suggest the removal of option `filetype`

**Comment by gaow** [comment]
Well, this is a feature I never used but I have read about it and though the VCF check was cool, without thinking deeper that it can be replaced by a parameter. So yes anything that makes the interface simpler without loss of functionality would be good move!

I assume with the use of `file` we'll have to save variables for both `file` and `input`, though. Maybe it is not a bit deal, because `file` is saved as a signature now (I think it was a recent change)? Otherwise maybe we can save only `_input` in this case, not `file`?

**Comment by BoPeng** [comment]
done. https://github.com/vatlab/SoS/commit/8b98a325ed528b565fff0f1b0ba0a1c6627b4338
