### ISSUE TITLE
Should R_library() and Py_Module() automatically install packages by default?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1069]
Currently R_library and Py_Module install packages automatically if not found on the system. Should this be the default behavior? There has been concerns raised for "polluting" the system software environment. Alternatively we can add an option `auto_install` and set it `False` by default, and quit with an error message that the library is not available and that users should either manually install or try to let SoS install by setting `auto_install` to `True`?

**Comment by BoPeng** [comment]
I had the same concern but have not got any better idea. I mean, the role of 

```
depends: R_library()
```
is to check if the R library exists, and attempts to install the library can be confusing. From a user's point of view, letting me know that I need to install something is common practice and is often good enough.

Instead of `auto_install`, I would prefer something like

```
[env: provides=R_library('whatever')]
R_install:
  whatever
```
and we can have something like

[setup]
cran_install:
   ....
bioconductor_install:
   ....
pip_install:
   ...
conda_install:
   ...
```

as a standard way to set up user environment, and these actions would of course just check the existence of packages before installation.

**Comment by gaow** [comment]
Okay so we do agree that we should change behavior of library / package check to quit on error. But I'm not sure if we want to make it any more complicated. In particular I do not see the appeal to define a number of new actions like `*_install`. Those installation commands are easy to type in full and users might want to add to them various command options. I think checking & quitting is good enough. Or, we can allow for:

```
R_library(..., install = None)
```

to not install,

```
R_library(..., install = 'default')
```

to use our current installation mechanism, and

```
R_library(..., install = 'step_name')
```

to run a step in SoS and check if the package exists after the step is complete? That way users can customize their steps of installation. It is also a lot more transparent. But I guess it is difficult to implement from what I know about the code ..

**Comment by BoPeng** [comment]
Whereas in-step `depends` is easier to write and maintain, centralized `-install` actions have the advantage of showing system requirement for the entire workflow. It also allows easier `sessioninfo` since we can report the versions of all these pip or conda packages in a centralized manner.

But the bottomline is that we can disable automatic installation.

**Comment by gaow** [comment]
I agree. Can we implement the `install` option and set it to `None` to disable for now, and worry about it later? Because the code in those actions that install the packages might be of relevance to future code refactoring that we do not want to delete at this moment.

Of course we'd have to rethink about it if this change is not good enough to do `sessioninfo` for workflows -- an important argument towards using SoS Notebook as SoS workflow IDE.

**Comment by BoPeng** [comment]
I do not have time for this (still struggling with zmq stuff) so I simply removed the installation part.... The tests are disabled and should be added later.

**Comment by gaow** [comment]
Okay, I would argue that down the line it is worth to support some R auto installation one way or another, because unlike with python there is no good unified command interface to install R libraries, and there is no (easy) way to specify which version to install from cran or bioconductor. It makes sense to streamline the defaults. I don't see a need for Python packages because pip and conda are clear and powerful without having to wrap them.

**Comment by BoPeng** [comment]
I have reverted the previous patch and added option `autoinstall=False` to the targets for backward compatibility reasons.

**Comment by gaow** [comment]
Yes I think it is a sensible solution. I think we can use another ticket to discuss different alternatives than modifying the existing R_library and Py_Module.
