### ISSUE TITLE
Check required packages when `-d` is specified to make DAG

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1070]
Currently without the following packages the `-d` will result in failure at the end of SoS execution,

```
conda install graphviz python-graphviz pillow imageio
```

It would be good to check for these 3 packages beforehand when `-d` is specified.

**Comment by BoPeng** [comment]
These things are tricky as the underlying libraries of graphviz and pillow might fail even if these packages are installed. Since this is arguably a less used feature (at least not required for the execution of workflows), I have set them as optional not required...

Also, these packages are not needed for the generation of DAG, but for the preview of DAG, so it does not make sense to check them unless `-p` is also specified because `-p` will render the `.dot` file to animation using these packages.

**Comment by gaow** [comment]
Oh indeed I meant to say that when `-p` is used it would be good to check this packages in advance.

**Comment by BoPeng** [comment]
Currently `zmq` is used to replace pipe (two way paired communication). The problem you report was caused by incorrect response of available process (slots) for the execution of concurrent substeps. It could be fixed but I am looking at more "zmq" way of handling such things, which will take a while...

**Comment by gaow** [comment]
^(wrong thread?)

**Comment by BoPeng** [comment]
Oh, should be #1056, but maybe I will just fix the concurrent issue in the old way and use a new branch for more advanced usage of zmq.
