### ISSUE TITLE
CPU & Memory usage for non-tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1084]
I seem to recall we keep track of peak CPU and peak memory usage. But a search in our documentation for "memory" or "ram" does not show any useful results. Where do we have the info? I assume it can be costly to keep track of them at all times -- do we have some action option for it, eg "resource_usage = 'xyz.log'"?

**Comment by BoPeng** [comment]
We do not keep have such information for non-tasks. The "trunk" of the workflow is supposed to be light-weight so there should be no need to keep track of CPU & memory usage.

**Comment by gaow** [comment]
Okay fair enough. Just checking. The user case is when I develop, for example, WGS calling pipeline for a single sample locally, I'd like to understand my resource usage. Would be nice to track them in non-task but not absolutely necessary. I'm cool to make it `wontfix` and close.

**Comment by BoPeng** [comment]
It is technically not that difficult to do, basically the controller can use psutils to get the memory and CPU usage of itself (the master process) and all the children, but I am hesitate to make it another rarely used feature since it can be easily done with an external script.

Actually this has been done here for the development of vtools. Basically our monitor.py is modified to be a wrapper (like command time) to start vtools and report CPU and memory usage after the completion of the command.

**Comment by gaow** [comment]
Yes indeed. I now simply do it via such an external script https://github.com/gaow/misc/tree/master/monitor
