### ISSUE TITLE
Current master and release broken for uninstalled R packages

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1093]
A MWE:

```
[global]
parameter: cwd = path('./mashr_flashr_workflow_output')
# Input summary statistics data
parameter: data = path("data/MatrixEQTLSumStats.Portable.Z.rds")
# Use vhat estimated from near NULL data
parameter: vhat = 1
# Use alpha = 1 for EZ model; 0 for EE model
parameter: alpha = 1
# Number of components in PCA analysis for prior
# default to 3 as in mash paper
parameter: npc = 3
parameter: mosek_license = file_target("~/.mosek.lic")
flash_data = file_target(f"{cwd:a}/{data:bn}.flash.rds")

[flash: provides = flash_data]
depends: R_library('mixsqp')
output: flash_data
bash: expand = True
  touch {_output}
```

Error message:

```
$ sos run test.sos flash
ERROR: not enough values to unpack (expected 3, got 2)
```

But if you replace `R_library('mixsqp')` with something you've got, eg, `ggplot2` it will work. Raising this because it has broken one of the pipeline on our end ... wondering if it will do the same for those workflow examples we updated a couple of weeks ago ...

**Comment by BoPeng** [comment]
I think the problem is at [here](https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L104) or [here](https://github.com/vatlab/SoS/blob/master/src/sos/targets_r.py#L131) which produce lines with two elements if `cur_version` is empty. I have pushed a patch that seems to fix the problem but it does not seem to be a robust solution because other parts of the line can contain space (package name, version, who knows). I suggest that you change `paste()` to `paste(sep='\t')` and `split` to `split('\t')`

**Comment by gaow** [comment]
I see. Will close this ticket after i make those changes. Thank you!
