### ISSUE TITLE
`docker_build` action problems

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1133]
I've got [this example to build docker image](https://github.com/gaow/jupyter-book/blob/7863a2064e1e4556e6c3777464a86f3f0b6830e0/release.sos#L28). The error message:

```
$ ./release.sos docker
INFO: Running docker: 
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM jekyll/jekyll:pages
 ---> 19aea80490a4
Step 2/4 : COPY Gemfile .
COPY failed: stat /home/gaow/Documents/docker/tmp/docker-builder232298147/Gemfile: no such file or directory
ERROR: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
script_7923499180869435001 in <module>
      RUN apk --update add make gcc g++ libc-dev
      RUN bundler install
----> """, tag = 'jekyll-book')

TypeError: replace() argument 2 must be str, not path
ERROR: [docker]: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
script_7923499180869435001 in <module>
      RUN apk --update add make gcc g++ libc-dev
      RUN bundler install
----> """, tag = 'jekyll-book')

TypeError: replace() argument 2 must be str, not path
```

You see there are two things:

1. COPY `Gemfile` failed for apparent reason. Why do we want to use a tempdir for building images? 
2. The type issue after.

**Comment by BoPeng** [comment]
The `replace` problem is easy. It was not tested because it is triggered by failed docker build.

The `COPY` issue is more complicated because the inline `Dockerfile` is moved to a temporary directory under the current directory and `COPY` expect the source of `COPY` to be under that directory. To solve this problem, we can either allow option `--workdir` and change directory there (but will overwrite existing `Dockerfile` there) pr add another option to copy files to the temporary directory.

**Comment by gaow** [comment]
It works, great!
