### ISSUE TITLE
cells need a min width value for when the console is closed 

### ISSUE THREAD

**Issue by andyjmc** [vatlab/SoS#1141]
![screenshot 2018-12-31 at 07 52 25](https://user-images.githubusercontent.com/42138224/50556450-334ea100-0cd1-11e9-8754-8c4a0669e7f4.png)

**Comment by BoPeng** [comment]
Could you let us know the steps to reproduce this?

**Comment by BoPeng** [comment]
https://github.com/vatlab/sos-notebook/commit/f3f2e7a1145eae93c8c8f8c9d3900f4a270ea773

Thanks for the report. This should have been fixed. sos-notebook 0.17.4 was released yesterday due to https://github.com/vatlab/sos-notebook/issues/168 and was not quite ready. It does contain all the UI updates we have done in the past few weeks so please let us know if you notice any other bugs.
