### ISSUE TITLE
SoS remote job hangs with incorrect job template

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1160]
I keep this `hang_test.sos.txt` around as a random diagnosis for SoS issues. Now with current `master` this test fails (and indeed hangs again!). For whatever reason. To reproduce on cluster:

```
cd ~/tmp/hang_test_cluster
sos run hang_test.sos.txt -c hang_test.localhost.yml
```

it will submit some jobs then hang. The submitted job status are `submitted` not `completed`. Maybe there is a user error on my end but whatever it is, the hanging behavior is not good and might suggest bigger issues. So I decide not to attempt fixing it but rather leave it as is for you to reproduce hopefully.

**Comment by gaow** [comment]
Okay the reason for the hang is because I asked stdout and stderr to be saved to a folder `~/ddd` which does not exist. I think we had once discussed this, that such error cannot be properly resolved? Or does it require system specific solutions that we have to add to templates?

**Comment by BoPeng** [comment]
> "asked stdout and stderr to be saved to a folder ~/ddd"

How did you ask it?

**Comment by gaow** [comment]
> How did you ask it?

Good point. Currently it is specified in the job template in config file, in my case `hang_test.localhost.yml`. But maybe we can consider making them some `task` options to reduce chance of potential mis-specification? That will make it robust against this particular issue. But would be nice to have a more general way to detect and respond.

**Comment by BoPeng** [comment]
SoS will only recognize `~/.sos/tasks/{ID}.err` etc (collect as part of task output). If you specify another path, it is purely a matter with the batch system  since SoS actions will [write to the default .err](https://github.com/vatlab/SoS/blob/master/src/sos/task_executor.py#L347), and the rest of the output will write to the file specified by template.

**Comment by gaow** [comment]
Yes I understand that and have no issue with it. The only problem now is if something is wrong with the template, particularly that part of the template, SoS will currently hang and the behavior is a bit confusing. I just changed the title of the ticket. What is confusing in this case is after jobs are submitted and failed instantly due to wrong path of `#SBATCH --output` and `#SBATCH --error`, SoS will not view the job as `failed` or `aborted`. Rather if you check the status it will always be `submitted`

**Comment by BoPeng** [comment]
Yes, we discussed this before, sos is trapped between `submitted` and `running` because in reality a task can wait forever. The only way to check this status is running the PBS status checking command but that is not done currently because we do not know when to run it --- running that for each task is not a good idea, waiting for whatever period of time, can also be slow for users.

**Comment by gaow** [comment]
>  but that is not done currently because we do not know when to run it

Right .. so we let it hang? Or anything you can think of to give some clues what is going on? I was thinking adding some `task` options like `stderr` and `stdout` which will specify the prefix and we take care of making the path if not exist. But I am not feeling very strongly about it.

**Comment by gaow** [comment]
Okay!
