### ISSUE TITLE
Some default packages no longer imported in global section

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1226]
This SoS script used to work:

```
os.system('ls')
```

but not now:

```
ERROR: [default]: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
script_8541286867558834409 in <module>
----> os.system('ls')

NameError: name 'os' is not defined
```

This will break some existing workflows. Other packages as far as I can tell now are `sys` and `glob`.

**Comment by BoPeng** [comment]
We introduced "default" packages before for convenience, and the ones we included are `os`, `sys`, and `glob`. However, when I worked on #1219, I realized that this is something that we did not document, and I do not want to document because

1. SoS is compatible with Python, but being able to run `os.xxxx` directly in SoS Notebook is not pythonic, and could be considered by some as a bug. (We did document that we provide `CONFIG` etc initially).

2. We are giving users something else to remember as "what are default modules?", "what modules are included as default modules"? "Can xxx be included by default as well"? Generally speaking, letting users use `os` directly causes more burden/surprise than the convenience it brings.

There are arguments on the other side but at this point when we try to formalize/document everything, I felt that we should not introduce yet another concept. I should have created a ticket to discuss/document this though.

**Comment by gaow** [comment]
> Generally speaking, letting users use os directly causes more burden/surprise than the convenience it brings.

Fair enough. I would not mind updating my various existing workflows to embrace the change. I'm cool to close this ticket if you like.

**Comment by BoPeng** [comment]
I could include them for backward compatibility but there is no way I could generate a warning message (or it is not easy to tell if a user has used `import os` by themselves) so allowing them would let more incompatible scripts to stay...
