### ISSUE TITLE
Inconsistency in group-passing behavior with/without output.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1328]
Running the following workflow

```
[10]
input: for_each=dict(i=range(3))
output: f'test_{i}.txt'
print(i)
_output.touch()

[20]
print(f'Input is {_input}')
```
we get

```
INFO: Running 10: 
0
1
2
INFO: Running 20: 
Input is test_0.txt
Input is test_1.txt
Input is test_2.txt
```

But running
```
[10]
input: for_each=dict(i=range(3))
print(i)

[20]
print(f'Input is {_input}')
```
we get

```
INFO: Running 10: 
0
1
2
INFO: Running 20: 
Input is 
```

The point here is that although  step 10 runs three substeps, step 20 only runs one substep because there is no output from step 10. A more consistent behavior seems to be generating three groups of empty `_output` and let step `20` run three times.

A bigger "problem" might be with the use of `group_with`. Basically, if we have `group_with` defined with an output,

```
[10]
input: for_each=dict(i=range(3))
output: f'test_{i}.txt', group_with=dict(var=['A', 'B', 'C'])
print(i)
_output.touch()

[20]
print(f'Input is {_input} {var}')
```
we get
```
INFO: Running 10: 
0
1
2
INFO: Running 20: 
Input is test_1.txt B
Input is test_0.txt A
Input is test_2.txt C
```
But the following workflow 
```
[10]
input: for_each=dict(i=range(3))
output: group_with=dict(var=['A', 'B', 'C'])
print(i)

[20]
print(f'Input is {_input} {var}')
```
will generate an error:

```
INFO: Running 10: 
0
1
2
INFO: Running 20: 
ERROR: [20]: [20]: 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
script_1985230152037254966 in <module>
----> print(f'Input is {_input} {var}')
      

NameError: name 'var' is not defined
```
Because `var` is not passed to three separate groups.

**Comment by gaow** [comment]
@BoPeng if  step `10` does not have an output, then it makes sense to expect step `20` to have empty input.  We can live with no `input` file but for `output` I think it is rather confusing to not have an actual file generated.  That is, `output: group_with=dict(var=['A', 'B', 'C'])` is conceptually confusing. Is there a reason you want to change the behavior? I think the current behavior is good ...

**Comment by BoPeng** [comment]
```
```

**Comment by BoPeng** [comment]
My argument is that we can always do

```
[10]
input: for_each=dict(i=range(3))
output: group_with=dict(i=range(3))

[20]
input: group_by='all'
```
if we want the existing behavior, but without the change there is no way to recover the group information from step `10`.

**Comment by gaow** [comment]
I agree that the change would definitely help with some user cases -- I was wondering what motivated it (eg a specific user case on your end). Essentially with the change:

1. we generalize `output` to including variables. 
2. there will always be an implicit `output` to pair with `input` (by the same grouping) whether or not it is specified. 

The problem here is that now `10` and `20` are sequential. Previously `10` and `20` will happen in parallel because there is no explicit output from 10 thus input of 20 does not depend on 10. But I guess it is a good feature anyways because numerically ordered steps should not happen in parallel anyways? For now I believe one has to use:

```
[1]
input: ...

[2]

depend: sos_step('deafult_1')
...
```

but the proposed change will elimate this natually.

**Comment by BoPeng** [comment]
> now 10 and 20 are sequential

This is not the case, at least by design. To make `20` indepdendent of `10`, it should have

```
input: None
```

BTW, I found that the new behavior could be explicitly enabled with

```
[10]
input: for_each=dict(i=range(3))
output: group_with=dict(var=['A', 'B', 'C'])
print(i)

[20]
input: output_from(-1, remove_empty_groups=False)
print(f'Input is {_input} {var}')
```

Since the default value for `remove_empty_groups` is `True`, the default input of `20` is currently something like

```
[20]
input: output_from(-1)
```
which is equivalent to
```
[20]
input: output_from(-1, remove_empty_groups=True)
```

Then what I was proposing would be changing the default value from `True` to `False`.

I frankly cannot recall why the default behavior was removing empty groups.

**Comment by BoPeng** [comment]
As an "application" for the new behavior, currently I am handling "errored" substeps with a `invalid_target()` so that one step can have

```
output_0
invalid_target
output_1
```
and then the next step would know
```
process output_0
ignore 
process output_1
```
which does not work when there is no `output_0` and `output_1` because originally the entire input is empty (remove empty groups) and would proceed, and would be a single `invalid_target` and be ignored. The new behavior will allow substep 0 and 2 to be executed (without input) while ignoring substep 1 due to previous errored substep.

**Comment by gaow** [comment]
Oh sorry I was wrong about the current sequential vs parallel behavior. 

Here is the post that introduced `remove_empty` https://github.com/vatlab/sos/issues/1198#issuecomment-458783004 we did not discuss the defaults there.

Since you are on `-e` features I'm going to post some tests to help checking `-e ignore` behavior. For my case, the input and output file names are given explicitly. So if previous step does not generate a file the next step can fail ...  I am hoping erroneous substeps can still be ignored in that case.

**Comment by BoPeng** [comment]
Thanks. The `-e` option is almost ready and I am continuing to add tests. As you have pointed out that there can be many different kinds of "errors" and current implementation might not have caught and handled them all.

**Comment by gaow** [comment]
Great! Thanks, I just posted the example to the other ticket. This is translating a simple DSC benchmark to SoS where I rely on such dynamic inputs and dependency of steps. We can discuss later if this is the best way to translate and execute benchmarks in SoS but for now figure out how to do `-e ignore` in that example -- of course unless you think it is better off using alternative implementation on my end and not bother with when working with dynamic inputs. I'm open to suggestions.
