### ISSUE TITLE
Deprecating options env and default_env of actions in favor of -r host?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1338]
Action level `env` has perhaps more control and allows something like

```
R: env={'PATH': '/path/to/R3.3'}
  script

R: env={'PATH': '/path/to/R3.4'}
  script
```

but in general I think `sos run -r` can be a more general way to control running environments of workflows. I personally do not use `env` and `default_env` and would propose the deprecation of these options.

**Comment by gaow** [comment]
I use `env` in the automatically generated DSC code but almost never use it when I write SoS scripts. It would be good to deprecate but not remove or warn about the deprecation.

**Comment by BoPeng** [comment]
What is your use case for such per-action use of env?

**Comment by gaow** [comment]
Instead of using some global paths for executables, for each "module" in DSC I allow users to setup specific path that works only for the module. That makes it easy to compare, say, different versions of same method. The SoS scripts are automatically generated anyways so it can configure it differently for potentially dozens of modules in a benchmark.

**Comment by BoPeng** [comment]
OK in DSC you intentionally allow the use of different `env` for different actions for comparison, this by itself seems to justify this parameter. `default_env` is different and says "if this var is not defined, use mine", which also could be justified in some cases.

Then do we want to extend it to make it more useful/flexible? There are endless possibilities here but I do not want to introduce a feature that overlaps with other features and difficult to use or rarely used.  I mean, `env` could be

1. A dictionary of environment variable as it is currently implemented.
2. A `conda env` or `virtualenv` to allow users to switch `env`. In my case I had a case that I am executing a notebook in a `sos` conda env, but I needed to run a command in a `cnv` env, and then the `cnv` env does not have `sos` installed and I cannot start the jupyter server there. I not sure how it could be specified or implemented. 
3. A more general but more difficult to use case can be a template (key in config). Like
```
env = CONFIG['myenv']['R3_3']
```
with
```
myenv:
    R3_3:
        module load R/3_3
        {command}
```

or even something like

```
env = CONFIG.get('myenv.R', R_version='3.4')
```
if there are parameters in `myenv.R`.

**Comment by BoPeng** [comment]
For the latter usage, a dedicated option `template` makes more sense, although this ticket is about reducing action options, not adding more. :-)

**Comment by gaow** [comment]
Suppose we want to test out different versions of software for an action, then indeed a way to switch `env` makes more sense (in DSC I hard-coded `env`  again because the script was generated anyways). Then I can imaging this:

```
parameter: context = 'myenv'
...
R: env=CONFIG[context]
```

Then in the current `env` dictionary in addition to `PATH` etc we can also support specifically `conda env`

**Comment by BoPeng** [comment]
OK, let us keep these two options then, and perhaps add `template` later.
