### ISSUE TITLE
should `depends` be interpreted before substeps are executed?

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1379]
I cannot easily reproduce it but i think this is related to #1375. Here is a MWE:

```
[global]
parameter: samples = path('1.txt')
parameter: chroms = [x for x in range(10)]


[filter_samples: provides = [f'{samples:n}.out1', f'{samples:n}.out2']]
input: samples
output: f'{_input:n}.out1', f'{_input:n}.out2'
print("I'm executed")
bash: expand = True
  sleep 3
  touch {_output}

[clumping_1]
depends: f'{samples:n}.out1'
input: for_each  = 'chroms', group_by = 1
output: f'{_chroms}.dat'
bash: expand = True
  touch {_output}
```

```
$ sos run test.sos clumping
INFO: Running filter_samples: 
I'm executed
INFO: Running filter_samples: 
ERROR: filter_samples (id=a952b03af38f236b) returns an error.
INFO: filter_samples is completed.
INFO: filter_samples output:   1.out1 1.out2
ERROR: [filter_samples (1.out1)]: [0]: Failed to obtain lock /tmp/gw/.sos/3ec690f110ffd286.lock for input 1.txt and output 1.out1 1.out2. It is likely that these files are protected by another SoS process or concurrant task that is generating the same set of files. Please manually remove the lockfile if you are certain that no other process is using the lock.
[clumping]: Exits with 2 pending steps (clumping_1, clumping_2)
```

The problem is that each substep in clumping depends on a step filter_samples, that can take a while to generate. So when substeps starts they don't see the depended file and they each ask for them, creating a race condition.

I guess this also holds for checking software availability / installing packages -- R/Python packages can be installed multiple times if every substep calls a depends that autoinstalls them.

**Comment by BoPeng** [comment]
I cannot reproduce this. Still trying.

**Comment by gaow** [comment]
Maybe try increase `chroms` and also use more `-j`, and increase `sleep`? Is it true that each substep will look for the dependencies and independently trigger the dependent step?

**Comment by BoPeng** [comment]
Because `depends:` is before `input:` it is actually processed only once, and the substeps will not be started before it is completed. 

Even in the case when you put `depends:` after `input`,

```
[clumping_1]
input: for_each  = 'chroms', group_by = 1
depends: f'{samples:n}.out1'
output: f'{_chroms}.dat'
bash: expand = True
  touch {_output}
```
The `depends` statement would be processed sequentially before substeps starts after all sos statements.

So you might have something else going on.

**Comment by gaow** [comment]
> it is actually processed only once, and the substeps will not be started before it is completed.

Oh okay this is good behavior. 

I'm sorry my example was overly trimmed. It has to be used in two steps, see below:

```
[global]
parameter: samples = path('1.txt')
parameter: chroms = [x for x in range(10)]


[filter_samples: provides = [f'{samples:n}.out1', f'{samples:n}.out2']]
input: samples
output: f'{_input:n}.out1', f'{_input:n}.out2'
print("I'm executed")
bash: expand = True
  sleep 3
  touch {_output}

[clumping_1]
depends: f'{samples:n}.out1'
input: for_each  = 'chroms', group_by = 1
output: f'{_chroms}.dat'
bash: expand = True
  touch {_output}

[clumping_2]
depends: f'{samples:n}.out2'
input: for_each  = 'chroms', group_by = 1
output: f'{_chroms}.dat2'
bash: expand = True
  touch {_output}

```

This will trigger the error.

**Comment by BoPeng** [comment]
```
rm *.out1 *out2; sos run test  clumping  -s force -j8
INFO: Running filter_samples:
I'm executed
INFO: Running filter_samples:
ERROR: filter_samples (id=b20940729fccfda0) returns an error.
INFO: filter_samples is completed.
INFO: filter_samples output:   1.out1 1.out2
ERROR: [filter_samples (1.out1)]: [0]: Failed to obtain lock /var/folders/th/qqjbxl1s5b35z0bmg047_p2w0000gp/T/bpeng/.sos/3ec690f110ffd286.lock for input 1.txt and output 1.out1 1.out2. It is likely that these files are protected by another SoS process or concurrant task that is generating the same set of files. Please manually remove the lockfile if you are certain that no other process is using the lock.
[clumping]: Exits with 2 pending steps (clumping_1, clumping_2)
```

So `filter_samples` were run twice, although it should be run only once. The problem is that

1. `cluming_1` and  `cluming_2` both do not have any input and depend on step `filter_samples`.
2. Since `cluming_1` and `cluming_2` are independent, `filter_samples` are called twice.

Usually the output are separated so `filter_samples` are ok, but in this case the step generates the same outputs, so there is a race condition.

**Comment by BoPeng** [comment]
The problem is that when we build the DAG, we see that the step is producing two different outputs, so they are called twice. Only when the step is actually executed would SoS know that there is an output statement that says otherwise.

That means we will have to actually look into the auxiliary steps during the building of DAG.

**Comment by BoPeng** [comment]
The ticket is valid, but are you aware of that fact that

```
[filter_samples: provides = [f'{samples:n}.out1', f'{samples:n}.out2']]
```
is actually
```
[filter_samples: provides = ['2.out1', '1.out2']]
```
so your
```
input: samples
```
is not matched from filename, rather defined from `parameter`.

**Comment by gaow** [comment]
Oh sure, thanks! I was being sloppy with this minimal example. We should be good in our actual workflow.

**Comment by BoPeng** [comment]
Now, for 

```
[clumping_2]
input: for_each  = 'chroms', group_by = 1
```
will take the output from `climping_1`, and each with an element of `chroms`, ...

So, it seems that you either do not need `for_each` and `group_by` or do

```
input: None, for_each  = 'chroms', group_by = 1
```

It took me a few minutes to see the problem here and I am wondering if how I can make this easier, at least let users know what is going on.

**Comment by gaow** [comment]
Ahh, sorry this is still a sloppiness from the MWE. Here is an updated example:

```
[global]
parameter: samples = path('s.txt')


[filter_samples: provides = [f'{samples:n}.out1', f'{samples:n}.out2']]
input: samples
output: f'{_input:n}.out1', f'{_input:n}.out2'
print("I'm executed")
bash: expand = True
  sleep 3
  touch {_output}

[clumping_1]
depends: f'{samples:n}.out1'
input: '1.txt', '2.txt', '3.txt', group_by = 1
output: f'{_chroms}.dat'
bash: expand = True
  touch {_output}

[clumping_2]
depends: f'{samples:n}.out2'
output: f'{_input}.dat2'
bash: expand = True
  touch {_output}
```

```
$ touch 1.txt 2.txt 3.txt s.txt
$ sos run test.sos
```

and we get the same error.

**Comment by BoPeng** [comment]
A patch is submitted, please test.

The root of the problem is

```
[filter_samples: provides = [f'{samples:n}.out1', f'{samples:n}.out2']]
input: samples
output: f'{_input:n}.out1', f'{_input:n}.out2'
```

SoS avoids evaluating any input or output statements during the building of DAG because they can be quite complicated. In your case, because `output` involves `_input`, SoS just uses the `default_output` provided by pattern matching. The `output` would be evaluated later when the step is executed, and everyone is happy.

In this particular example `output:` has to be evaluated to determine the real output is different from `default_output`, so I will have to evaluate `input`, then `output`. Because they are executed in an incomplete environment, things can go wrong here. In particular, substeps are not allowed here (`step_input == _input`), although i guess no one has used substeps in auxiliary steps.

**Comment by BoPeng** [comment]
I have reverted this patch because it broke a few tests. I am investigating.

**Comment by BoPeng** [comment]
Yes and no, because when an auxiliary step is really executed, it will have a context that is passed from SoS, and should be able to dynamically trigger another step, and it also allows substeps. In the DAG stage, SoS simply tried to evaluate the `output` if it is simple enough, and guess the `output` of the step using lexical analysis (named output etc) if failed, and give up it is too complicated. The bottomline is that it does not attempt to run the step.

Your example would work if

```
[step: provides=['{sample}.txt', '{sample}.out']]
output: '{sample}.txt', '{sample}.out'
```
because `sample` would be known from filename matching. Unfortunately, you did something like

```
[step: provides=['{sample}.txt', '{sample}.out']]
input: sample
output: '{_input}.txt', '{_input}.out'
```

so SoS failed to get `output`.

I tried to evaluate things before `output`, which worked for your example but broke some tests so I am re-implementing the change.

**Comment by gaow** [comment]
> Your example would work if ...because sample would be known from filename matching. Unfortunately, you did something like

Okay I see that was what you tried to tell me yesterday it seems. Indeed that bit is the same in my workflow and in the MWE. I can change that by doing what you suggest. 

But do you still see it as a bug or user error?

**Comment by BoPeng** [comment]
Any thing like "too many open files", "unable to get lock" would be a bug on the SoS side, since sos should either run without problem or point out what is wrong with the script.

In this particular case I tend to generate an error and let users know that the SoS needs to know the output. However, as I said I do have tests like this and ran well because the steps are not triggered from two different input files that generate two nodes to be executed at the same time...

**Comment by BoPeng** [comment]
OK, your example should now work, and all tests pass now.
