### ISSUE TITLE
Workflow on compute node doesn't update hosts.yml

### ISSUE THREAD

**Issue by pgcudahy** [vatlab/sos#1434]
I've got my scripts up and running with the new option to submit the workflow to a cluster compute node and it's great. Thanks for all the work on cluster support over the last few months. One slight thing I noticed while I was iterating things to get them working is that my local hosts.yml is copied to `~/.sos/config_{self.alias}.yml` on the cluster. However, if I update my local hosts.yml and then submit a new workflow to the cluster from my local notebook, the cluster `~/.sos/config_{self.alias}.yml` file doesn't get updated. Shouldn't these be kept in sync?

**Comment by BoPeng** [comment]
Thanks for the report. It looks like a glitch that the config file failed to upload when a remote copy already exists. I will have a look.

**Comment by BoPeng** [comment]
This should have been fixed. I will make a new release as soon as #1424 is tested.

This is due to an `--ignore-existing ` setting in sending the config file to remote host. The function was designed to send task files, which would have different names if the content change so there is no need to send a task file that already exists on remote host.

**Comment by pgcudahy** [comment]
Thanks very much
