### ISSUE TITLE
SOS not break when bash step produce error in all but the last command

### ISSUE THREAD

**Issue by hsun3163** [vatlab/sos#1456]
Hi Bo, thank you for promptly addressing the previous issue. A new problem emerged.

The following example:
```
[default]
output: "1.txt"
bash: expand = True
  non_existing_tool
  touch {_output}
```
Produce 
```
hs3163@node53:/mnt/mfs/statgen/snuc_pseudo_bulk$ sos run test_2.sos
INFO: Running default:
/tmp/tmpc3znvekc.sh: line 1: non_existing_tool: command not found
INFO: default is completed.
INFO: default output:   1.txt
INFO: Workflow default (ID=w6a4d7d08c4a4602a) is executed successfully with 1 completed step.
```
While it is expected to break after the first line. However, as indicated above, the sos run successfully.  In fact, the step will only break when the line `non_existing_tool` is the last command.

I am aware that this issue can be fixed by 
```
[default]
output: "1.txt"
bash: expand = True
  non_existing_tool && \
  touch {_output}
```
Or 
```
[default]
output: "1.txt"
bash: expand = True
  ser -e
  non_existing_tool 
  touch {_output}
```
However, I wonder is there any built-in feature in sos to fix it?

**Comment by BoPeng** [comment]
This behavior is by design since this is the default behavior of `bash`. If you run the script
```
> cat test.sh
non_existing_tool
touch 1.txt
```
with command

```
> bash test.sh
test.sh: line 1: non_existing_tool: command not found
> echo $?
0
```

bash does not produce an error.

However, the `run` action by default uses `bash -ev` on linux so the `run` action should get what you want. 

See [documentation](https://vatlab.github.io/sos-docs/doc/user_guide/shell_actions.html) for details, but if you really want to use `bash`, you can use `bash: args='-e {filename:q}`.
