### ISSUE TITLE
A confusing debug message on keyword `task`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#336]
I get this message with `-v4` for any script involving `task`:

```
DEBUG: Args concurrent = True
 cannot be determined: Unrecognized directive task
```
It does not impact the execution of the SoS script, but is just a bit confusing / annoying.

**Comment by gaow** [comment]
Here is perhaps a related issue so I'll use this ticket. The example:

```
[1]
n = ['1.txt', '2.txt']
input: for_each = ['n']
output: _n
task: concurrent = True
run: 
  touch ${_output}
```

and with `-v4` mode I see:

```
DEBUG: Workflow default created with 1 sections: default_1
DEBUG: Args _n
 cannot be determined: name '_n' is not defined
INFO: Executing default_1: 
```
but it is able to execute without an issue.

**Comment by BoPeng** [comment]
This piece of code is  used to analyze (before execution) the step to determine input and output for the initialization of the DAG. If a variable is used instead of constant filename for input and output, the input/output is assumed to be dynamic (unknown) and would be executed after previous steps.

**Comment by gaow** [comment]
This message causes no harm and it is perhaps not good practice to use `_n` anyways (instead of "{_n}" which I believe most people would do). So there is no need to fix it if the patch is ugly.

**Comment by BoPeng** [comment]
You can reduce the message to `trace` if it bothers you.
