### ISSUE TITLE
R_library() signature issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#416]
Here is the MWE:

```
[1]
depends: R_library("plotly")
output: '1.txt'
run:
 touch ${output}
```

Executing this script multiple times does not trigger rerun, but if R_library() is removed the behavior is good. It seems the runtime info parser does not like R_library(), if we turn on `-v4` and read the outcome.

**Comment by BoPeng** [comment]
This is because `R_library` [is not recognized during signature validation](https://github.com/vatlab/SOS/blob/master/sos/target.py#L619) after I moved these signature types to separate modules. This is unavoidable because there would be different types of targets anyway. The validation of signatures of these would have to go another way around ... later though.

**Comment by BoPeng** [comment]
Thanks for the `entry_point` mechanism that we can get the class of all targets ...
