### ISSUE TITLE
Jupyter notebook stops at first cell

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#434]
I have encountered this more than once. When I open a sos notebook, execute the first cell, the cell would appear to be executing (with `In[*]`) but never returns. Cannot figure out a reason for now.

**Comment by BoPeng** [comment]
Another symptom is that executing statement in panel cell would select cell in the main notebook.

**Comment by BoPeng** [comment]
It appears to be a symptom of #400

**Comment by BoPeng** [comment]
The real problem is more complicated (https://github.com/jupyter/help/issues/153#issuecomment-289026056) and hopefully (https://github.com/vatlab/SOS/commit/973264bc9373c2135739dcf468c37b5b81228988) has fixed it.

**Comment by gaow** [comment]
Great to have you back :) I just upgraded. It does fix other related issues I keep pulling my hair for. I think we talked about having to restart Jupyter each time to have SoS kernel work properly but sometimes no matter how many times I restart it still does not work. Anyways this patch at least solved something. 

I'm also running into issues with `task` but I did not want to distract you earlier -- because there is a pile of them ... as far as i can recall those include:

1. It seem to work only for the first element in `for_each`
2. It sometimes quits on error asking me to execute codes that actually run well by themselves
3. The Jupyter GUI to monitor tasks does not reflect what in fact was going on

these issues are gone once I remove `task` so I had to stick without running `task` recently, on my desktop. It is not easy to come up with MWE. If I still cannot come up with MWE today I'll just try to organize and share my production code for a test.

**Comment by BoPeng** [comment]
I have other duties but at least no urgent deadline so I am trying to clear up some annoying issues. The dead-on-first-cell one has been bugging me for a while so I finally decided to talk to the Jupyter developers... and that helped.

I have been using tasks with limited success, meaning that I know what went wrong and what to do if things went wrong. For your problem,

1. I did not notice this.
2. The task needs to be self-contained and we can only pass global variables to the task, not modules and things of that nature. I mean,

```
import time
task:
  time.sleep(5)
```
will not work. You have to do

```
task:
  import time
  time.sleep(5)
```

3. We need more states (there is a ticket for this) because it only reflect the status of sos task queue, not pbs queue status. Also things can get complicated when there are previous tasks (succeed, failed, succeed without output, still running, etc).
