### ISSUE TITLE
Interface for removing obsolete task files.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#485]
A single task could have `.task`, `.status`, `.res`, and engine specific files such as `.pbs`. Over time, sos tends to accumulate a large number of such files, which, in addition to file management issues, actually could slow down sos because `sos status` matches all jobs and query them all.

We of course do not want to remove running jobs, also jobs from the same batch because they are still actively monitors, and perhaps not "unknown" jobs because they might be submitted from another machine. I suppose this has to be a manual process using something along the line of

```
sos remove --completed
```
and
```
sos remove --failed
```
and perhaps
```
sos remove --tasks
```

Another possibility is to archive these files... zip them and allow sos to retrieve them later on. 

Any comment?

**Comment by gaow** [comment]
This is perhaps easier if each task has unique ID ... then at each rerun, can we automatically skip / remove the ones that are have failed? Are these files stored in the local `.sos` folder? I suppose keeping the completed job status is desirable so automatically removing only the failures and having them in the local `.sos` is acceptable, in terms of amount of files it leaves behind.

**Comment by BoPeng** [comment]
This is already the case. Re-run the same task will overwrite previous files. All files are stored in `.sos/tasks` with translated version stored in `.sos/tasks/engine_alias`. The remote host has them also under `.sos/tasks`.

**Comment by gaow** [comment]
I'm not sure if rerun will overwrite previous files ... I have had a few runs under my current SoS folder, but when I type `sos status` it seems to be showing everything that has been done before, including the ones from other SoS projects. Most of them are labelled `dead`. I was expecting `sos status` only shows the ones under the current project, and if the project is executed again then all the `dead` ones should be automatically wiped out. In that way we should only have a local list of tasks depending on where `sos status` is executed, and there will not be `dead` tasks if the same task is being re-executed. That's why I thought having non-random ID would help.

**Comment by BoPeng** [comment]
Then something might have changed to generate new IDs for the tasks, and the old tasks will stay at the global `.sos/tasks` forever.

The problem here is that you might run different workflows or with different parameters so you "current" tasks are not all your tasks. Also, other projects might be producing the same tasks ... Not sure how to resolve this.

**Comment by BoPeng** [comment]
I think the solution would be similar to signatures... we record tasks in local workflow signature files (`.sos/*.sig`), and we only show status of tasks that are recorded there.

**Comment by jmelott** [comment]
Have you considered creating a subdirectory for each SoS project and putting all the related information for that project under that subdirectory?  Then when reporting status, SoS would just need to look for that directory and check the information under it.  Otherwise, if you start putting thousands of files in the same directory, the system will start to slow down just due to the directory searches without even looking at the actual data stored in the files.  This could also make it easier to move data for a project from one project or machine to another in the future if such a feature were needed as you'd only need to copy or rsync the single directory related to that project.

**Comment by BoPeng** [comment]
Right now, for example, if I submit jobs from my workstation to the cluster, we have 

1. `.def` files under `~/.sos/tasks` on workstation
2. translated `.task` files under `~/.sos/tasks/nautilus/` on workstation
3. translated `.task` files under `~/.sos/tasks/` on cluster

Then, if I am at home, I can run

```
sos status -q nautilus
```

to check the status of the jobs because this command would log in to nautilus and get status of all tasks.

Another consideration is that tasks are currently designed to be independent of workflows. Say I have two workflows that analyzing the same data and share the same first time-consuming step, the task would be shared by two workflows. 

Saving `.tasks` files under a project directory would disable both these features.

That said, each project do have a `.sos` directory to save project-specific information and it is possible to store at least IDs of tasks there. In this way, when we do

```
sos status
```

it will by default only query the tasks related to the current project.

Users would still be able to do 

```
sos status --all
```
to check the status of all tasks.

This does not address the ticket, namely how to remove obsolete task files so we might be look at something like

```
sos remove --tasks
``` 

to remove tasks related to local project,

```
sos remove --tasks --all
```
to remove all local tasks,  and

```
sos remove --tasks --all -q nautilus
```
to remove all tasks on remote server.

Note that `sos remove` is being redesigned #543

**Comment by BoPeng** [comment]
Practical options include removing

* all tasks
* tasks that older than certain days etc (see output of `sos status`)
* all completed, failed etc.
