### ISSUE TITLE
Concurrent processes for non-task actions

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#530]
I'm running into various issues with `task` that I should report soon. But still I think for computations running on local desktop I'd rather not use `task` because it is otherwise much simpler to manage (I'll not have to worry about status or zombie processes). That'd essentially be what we have before (in the last release). The issue now is that without task I can only run it as a single thread process. I'm wondering if we can easily allow for multiple thread in that case -- basically ask non-task jobs to honor `-j`.

**Comment by BoPeng** [comment]
Only tasks allows for `concurrent=True`, so you are out of luck if you are talking about multiple tasks in one step because `-j` works at the DAG level. 

If you are worried about zombie tasks, how about we do not use the double-fork trick for `-w` mode so that tasks will be killed when the master process is killed? This way you will have task (and local queues) without the risk of zombies.

**Comment by gaow** [comment]
Yes that'd be very helpful. I always like to run with `-w` on my desktop and I do expect killing the master process will end everything :)

**Comment by BoPeng** [comment]
That is easy ...
