### ISSUE TITLE
Recursive variable exchange

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#572]
We have several types of variable exchanges in notebook:

http://vatlab.github.io/SOS/doc/documentation/Notebook_Interface.html#%put

I'm wondering if we can make it recursive so that I can potentially have a dictionary / list of any arbitary data types in this table, or even dictionary of dictionary of these types, and exchange that cross kernels. I am asking because I often find it convenient to write all output information from a computational procedure to a dictionary (or List in R) for use in the next language.

**Comment by BoPeng** [comment]
It is supposed to be recursive between Python and R, you can try and let me know what does not work.

**Comment by gaow** [comment]
Great! I'll test it out. Also is there a utility function that we can take advantage of in batch mode? For example it is tempting to write

```
from sos.utils import put, get
[1]
output: 'res.out'
task:
R:
  result = computation()
  put(result, ${output!r})

[2]
output: 'res2.out'
task:
python:
  res = get(${input!r})
  res = computation(res)
  put(res, ${output!r})
```
Would be great to be able to use this!

**Comment by BoPeng** [comment]
That is a completely separate issue because currently data exchange occurs between live instances (kernels) and mostly happen in memory. What you have in mind is very complex and well beyond the scope of SoS.

**Comment by gaow** [comment]
I see. I'll close this for now until I run into problems inside a notebook.

**Comment by BoPeng** [comment]
Due to differences in data types and models, there is certainly no lossless way to implement the save to file and load from another language feature. However, if we stick to a common data type, it is possible to exchange a subset of datatypes. This is more or less like a network protocol where the data type is pre-defined and the client can be implemented in any language. The obvious disadvantage of this approach is that the format cannot handle large and complex datatypes like dataframe.

The format of choice is obviously JSON, which is widely supported by many languages. I do not think it is wise to implement modules/libraries for different languages in SoS but we can keep track of JSON support in different languages.

* Python has [pyYAML module](https://pypi.python.org/pypi/PyYAML).
* R has [jsonlite](https://cran.r-project.org/web/packages/jsonlite/vignettes/json-aaquickstart.html)
* Matlab has [JSONlab](https://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files?requestedDomain=www.mathworks.com)
