### ISSUE TITLE
Consequence of external removal of tracked files.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#591]
#543 raised the issue whether external `rm -rf` should trigger rerun. The current design is that the workflow would skip steps as long as file signatures are present, which is the case for `rm -rf` because that command does not remove signatures. The behavior can be confusing because some times steps seem to be mysteriously skipped.

If we are to trigger rerun with the removal of files, we would need to  change test for `target.exists` from `any` (namely `signature` or `target`) to `target`. This is almost trivial but raises the question as how to remove large intermediate files without rerun.

### Solution 1

Put signature next to file so that `rm -f file*` would remove `file` and `file.sig` and trigger rerun. In contrast, if a user remove a file without its signature `rm -f file`, the step would skip.

Pros:
1. seems to be easy to understand

Cons:
1. Contaminate file system with signature files.

### Solution 2
Use special command to remove file. For example, use command `sos remove file` to replace `file` with `file.sig` in user's file system.

Pros:
1. Less contamination of project directory because only files that are replaced with their signatures are different. 
2. This also allows users to remove `.sig` file outside of sos to trigger rerun.

Cons:
1. Special command to replace files with their signatures. 

### Solution 3
Use special signatures after using command `sos remove`.

Pros:
1. No contamination of project directory

Cons:
1. Confusing if no file is in project directory.
2. After the file is "removed", another special command is needed to really remove the file.

**Comment by gaow** [comment]
Triggering rerun via `rm -f` is a convention of `Make` as well as possibly a number of workflow systems. So the "Pros" here is apparent. Another important argument is that I think in practice there are more user cases that we want to remove unwanted files (due to experiment failure) and trigger rerun -- this is the "research mode". Removing intermediate large files without triggering rerun often happens when a pipeline is somewhat mature and the product reliable -- this is the "production mode". I cannot speak for others, but at least I find myself in research mode a lot because I just couldnt get things work most of the time ... my office mate also expects this behavior. Therefore Solution 2 is most intuitive for us.

**Comment by BoPeng** [comment]
I also tend to like solution 2 so I will implement this one.

Regarding production mode, do we need to provide some action to help removal of large files? something like

```
impersonate(files)
```
to replace files with their signatures to reduce file size.

**Comment by gaow** [comment]
I think it is good enough to have `sos remove --size`. It is perhaps good idea not to mix up maintenance and pipeline code, because a different input to the same pipeline would result in files of different sizes.
