### ISSUE TITLE
Suggestions to %sossave

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#594]
Not entirely necessary, but I'm wondering if adding two options to `%sossave` would be a good idea:

1. `-f` force rewrite existing script
2. `+x` change mode to executable so that later we can run `./xxx.sos`

**Comment by BoPeng** [comment]
There should be a force option.

**Comment by gaow** [comment]
I do not think adding `-f` or `--force` works

**Comment by BoPeng** [comment]
The parser is at [here](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.py#L306) and the code is at [here](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.py#L1724), I suppose you can make it work. :-)

I doubt if we should [add `.sos` extension](https://github.com/vatlab/SOS/blob/master/sos/jupyter/kernel.py#L1722) though because users might want to save to an executable without `.sos` extension. Please remove it.

**Comment by gaow** [comment]
It should be fixed now.

**Comment by BoPeng** [comment]
Does `filename = self._notebook_name` include prefix? If not, should we add `.sos` to notebook name?

**Comment by gaow** [comment]
Great point! I just committed a patch.

**Comment by BoPeng** [comment]
Thanks.

**Comment by BoPeng** [comment]
Another point is that if there is no side effect of changing mode, perhaps we can always change it (without `-x` option).
