### ISSUE TITLE
Remote tasks submitted from a laptop

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#610]
I'm asking this on behalf of laptop users: submitting jobs directly from the HPC system is easier for laptop users because they can submit, logout, fold the laptop screen and move on to their next physical destination. With SoS it is a bit harder because we have to keep a process running to monitor jobs and rsync data. Is there any best practice recommendation for working with laptop type of setup? (in my office area there are many more laptops than desktops).

**Comment by BoPeng** [comment]
Unless you are running in `wait` mode (with option `-w`), sos will quit as soon as the jobs are submitted and there is no need to keep a processing running to monitor jobs.

If the results are supposed to be synced back to users laptop, they need to run the same workflow with `-r` (`--resume` mode) option to fetch the results of completed tasks and complete the workflow.

**Comment by gaow** [comment]
Yes that's good enough. My colleague and I were talking about being able to resume automatically after open the lid of laptop (after sleep not hibernate -- not sure the proper Mac term for it) etc as he tends to roam a lot in the building. But I do realize we were hoping too much out of it :)

**Comment by BoPeng** [comment]
Resuming by itself like that is physically not possible :-) since the remote connection has been ended. If you have not noticed, the jupyter notebook actually does auto-resume if you do not close the notebook. That is to say, it will automatically resume itself until the task is completed cleanly.

**Comment by gaow** [comment]
Oh actually that notebook function is exactly what we were hoping -- that we do not have to worry about resuming manually from time to time whenever laptop is fold or wifi is lost (happens a lot in my buliding). I have to admit I'm not using Jupyter for remote task but I should now ...

**Comment by BoPeng** [comment]
Jupyter is just a frontend of the command line so it should also have the `submitted` problem. The auto-resume feature of jupyter also needs network though. 

Actually there are strictly speaking two types of status, status of tasks on local and remote machines (`sos status -q`),  and status of workflow. That is to say, after you submit a workflow and quit, there should be some command to check the status of the workflow, something like

```
sos status --workflow ID
```
where ID could be ignored for most recent workflow. This command should know where the tasks has been submitted and check its status, and perhaps also fetch the results if the tasks have been completed. This way users do not have to remember what command and options they have used in order to resume the exact workflow.

**Comment by BoPeng** [comment]
Also, `sos run -r` should not need all the previous parameters....

**Comment by BoPeng** [comment]
Ok, the new `sos resume` command can be execute without option from any directory, which should significantly simplify the resumption of workflows. This is [documented here](http://vatlab.github.io/SOS/doc/documentation/External_task.html#sos-resume-195). Please test and report back.

**Comment by gaow** [comment]
I see `-r` is removed from `sos run` too. This is great. I'll report back if I run into issues.

**Comment by BoPeng** [comment]
-r is just hidden as sos resume calls it if needed.
