### ISSUE TITLE
Remote execution of workflow 

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#621]
#475 

It was proposed that there can be a global remote mode where all input, output, and depends are supposed to be on remote host. This sounds like an appealing method to execute an entire workflow remotely, but we will need to define the behavior of SoS clearly before we even think of an interface.

Questions:

1. What about files that are not input, output, or depends?

2. What if the logic of a next step depends on the result file that is currently on the remote machine?

3. What to do with simple operations such as `len(input)` when `input: '*.txt'`? I suppose the current `input: remote('*.txt')` has the same problem.

4. Would it be easier just to execute entire workflow on the remote server? 

5. What to do with steps without task? That is to say, if we have a normal step

```
[10]
input: 'a.txt'
print(input)
```

Since `input` is on the remote machine, it makes sense to execute the entire step on the remote host. We cannot use task queues for this (because of no `mem` definition etc) so we will have to execute the task on the head node (namely assuming `process` queue on the head node)....

**Comment by gaow** [comment]
> What about files that are not input, output, or depends?

It is then the user's responsibility to ensure they exist. But isnt it bad practice to even have such files? I always try to make all files to belong to one of these categories ... 

> What if the logic of a next step depends on the result file that is currently on the remote machine?

We are talking about a global remote here so this concern should better fit #475. Here I'm happy to just properly quit on error (file not found) because perhaps it's a typo rather than a desired behavor when this happens, and it would be nice to give users a chance to fix . 

3 `len(input)` is a hard one ... unless we treat them case by case. How many cases we need such special operations?  If it's just getting remote file names from wildcard we can somehow run an inline python function on remote via ssh and take the stdout in place for these wildcards?

> Would it be easier just to execute entire workflow on the remote server?

It is easier, but not always possible, to have a long running master SoS on the login node. But again automatically converting all file targets to be remote we'd avoid 2. Also I see 3 a perhaps corner case.

**Comment by BoPeng** [comment]
`remote` is quite new so let us just put `remote` on where it is needed for now, and see if there is really a need for global `remote`. It would be awkward if we have to introduce something like `local` object if we have a global `remote` mode. Anyway, we have removed `sos -r` so at least we have a flag for this mode.
