### ISSUE TITLE
Public Jupyter server headache

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#665]
The public jupyter server has not been running well. Upon close inspection, the server is running on a tiny VM with only 1 G of RAM so it might have been swapping. I upgraded the VM but I am getting some proxy error. Upgrading Jupyter inside the VM produces some authentication error.

Perhaps @jma7 can have a look and fix the issue but it might be easier just to shut off the service.

Note that I have another ec2 instance of the server at http://ec2-34-226-117-10.compute-1.amazonaws.com:8000/

**Comment by gaow** [comment]
It would be nice to show a server with example notebooks to load and try out. I can provide a machine's IP that we can host the server, if we have a URL domain that we can forward it to, until we find other options. Is that Ok? Please let me know what I need to do as `sudo`; or give me specific instructions (bash history) to set it up. After than I assume without `sudo` we can all manage it?

**Comment by BoPeng** [comment]
There is no need for a domain name because we are free to change the URL of the `try me now` button. Do you really have a machine (or VM) that can be accessed from anywhere (no firewall) and always on? Jun has set up an ec2 instance and recorded the steps in #139 and he consulted steps in [here](https://github.com/econchick/scapy-tmpnb). My problem is that after I set up the machine on another ec2 instance, the page asks for a token, and we need to set token to '' to disable it as instructed [here](https://github.com/jupyter/tmpnb/issues/256), and at that point I lost patience.

**Comment by gaow** [comment]
I do have a machine with a static public IP initially purchased to server some shiny app but it is barely used as of now. It's always on. It has 16GB RAM which I can maximize to 32GB if needed (just plug in a couple of chips). The problem is that the machine only has a public IP. Not sure without a domain name how it can be connected without using the IP address. 

From Jun's not it does seem the only think I need to install is docker? I just installed it. Is that all we need? I've sent the login info to you with a private ticket.

But I see the problem now is about having to set a token? I imaging on my machine the same will happen?

**Comment by BoPeng** [comment]
I think we need to modify the docker to have a jupyter configuration file to disable docker. Basically you start the docker image, see if you need token, then ssh to the image, try to add a configuration file and restart the jupyter server and see it removes it. Then you can modify the Dockerfile....

**Comment by BoPeng** [comment]
I have terminated our amazon aws ec2 instance, and should have our local server running before we submit the manuscript.

**Comment by BoPeng** [comment]
The button for public server has been removed from homepage, which could be restored after we set up another one.
