### ISSUE TITLE
Difference of valid variable names between Matlab and Python

### ISSUE THREAD

**Issue by HenryLeongStat** [vatlab/SOS#706]
In Matlab, the variable names beginning with underline(_) are not the valid variable. However, it is valid in Python. So it might cause some problems. Although it is a tiny problem, I think we should specify that in the documentation.

**Comment by BoPeng** [comment]
We handle this problem by automatically rename the variables, check [this code for R](https://github.com/vatlab/SOS/blob/master/src/sos/R/kernel.py#L250) for details.

**Comment by HenryLeongStat** [comment]
I see! It's exactly the same problem in Matlab.

**Comment by BoPeng** [comment]
I am re-opening the issue because it is not addressed in [`Matlab\kernel.py'](https://github.com/vatlab/SOS/blob/master/src/sos/Matlab/kernel.py#L128) (code is copied from R and commented).

Note that a commit can refer to this ticket with "#706" in commit message, even close the ticket with "close #706"

**Comment by HenryLeongStat** [comment]
OK. Maybe I can try to handle it!

**Comment by HenryLeongStat** [comment]
Since a valid variable name in `Matlab` must be starting with a letter, I suggest to use `Ml_`(captial M + l + underscore, which is the short form of `Matlab`) as the prefix without any confusion.

**Comment by BoPeng** [comment]
Since the variable already starts from something like underscore (e.g. _fun), i would suggest that we simply add m before it (e.g. m_fun).
