### ISSUE TITLE
Default number of tasks for `-J`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#717]
I'm running some scripts on my laptop virtual machine (never have tried that before until today at a teaching session) with default `-J` option. It keeps falling apart and from the error message I see it runs out of memory. When I change `-J 4` it works. Should we reduce its default setting? Or, is there a way to set it in `CONFIG` that will be used by default but can also be overwritten by `-J`?

**Comment by BoPeng** [comment]
`-J` overrides host option `max_running_jobs` so you could reduce it by

```
sos config -g --set hosts.localhost.max_running_jobs 4
```
although without testing I do not know if this works if you do not have anything else defined.

We could also reduce the default value for `process` queue type because compared to real task queues on a cluster, concurrent running jobs should perhaps be smaller.

**Comment by gaow** [comment]
I suggest setting default to `max(int(os.cpu_count() / 2), 1)`

**Comment by BoPeng** [comment]
I am fine with this.
