### ISSUE TITLE
Support for Python Series datatype to R.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#747]
The Pandas Series type does not seem to be supported and I get "unsupported datatype" when trying to send it to R.

**Comment by HenryLeongStat** [comment]
I have checked the kernel and found that it isn't specified yet.
For `Pandas.Series`, it has the `index`, so should we just convert it as `vector` in R? Or we convert it as `dataframe` in R?
For the former case, it would be more likely to be a `series` (as it's one-dimensional). However, the index would be lost. 
For the latter case, the information of `Pandas.Series` would be saved. However, it would become a dataframe instead of vector. 
I suggest we should save it as the dataframe, as it won't lose any information of the data.

**Comment by BoPeng** [comment]
R vector can be named , see [here](http://www.r-tutor.com/r-introduction/vector/named-vector-members) for a tutorial.

**Comment by HenryLeongStat** [comment]
A problem comes up when I modified the `test` for `R`. For now, a `R` `named vector` would become a `list`, which without index in `sos`. So it becomes a problem for `R` `named vector` -> `sos` `?` 
Should we convert the `R` `named vector` -> `sos` `pandas.Series`? Or `R` `named vector` -> `sos` `dict`?

**Comment by HenryLeongStat** [comment]
For now, in `R`, `list with names n > 0` would be converted to `dict` in `sos`.

**Comment by HenryLeongStat** [comment]
I open a new issue at #754
