### ISSUE TITLE
Row label of dataframes get lost in Julia DataFrame.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#788]
The same problem as #397 , we will need to pass row labels manually (see kernel R for details )

**Comment by HenryLeongStat** [comment]
Yes, I marked that before. Will fix it soon.

**Comment by HenryLeongStat** [comment]
Searched the [documentation](https://en.wikibooks.org/wiki/Introducing_Julia/DataFrames) and the [internet](https://groups.google.com/forum/#!msg/julia-users/8UFnEIfIW0k/QNEustV9BQAJ). It seems like if we want to name the row, the datatype needs to be `named.array` instead of `dataframe` because in `dataframe` package, it seems `naming row` isn't supported yet (or didn't mark in the documentation). 

One thing we can do here is that in `python`, if there is `row name`, we add it as the first column of the dataframe in `Julia`. Since there is no `row name` in `Julia.dataframe`, so there are just 2 situation:

1) python.pandas.dataframe -> julia.dataframe `with row name` (i.e. 10x10 in python, 10x11 in julia and the first column is `row name`)
2) python.pandas.dataframe -> julia.dataframe `without row name`


I just remember I had searched about that last week....

**Comment by BoPeng** [comment]
OK, it does not make sense to change the dimension of array so I just submitted a patch to give a warning message in this case. The doc has also been updated.
