### ISSUE TITLE
[global] section scope

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#805]
Separated from #802 

This scope issue with `[global]` often bothers me. What I usually do in research is to prototype using some local cells with loose SoS statements, and after my codes are tested I put them to formal steps to execute. This inevitably involves using global variables in both inside and outside steps. With the current SoS implemention I usually find myself having to define one same variable twice: one under [global] to let workflows use them, one as a local statement for interactive analysis. It would be great if we can make this part easier.

**Comment by BoPeng** [comment]
What would be your proposal? Automatically execute all `[global]` definitions in a notebooik for the execution of local cell? This can be a bit annoying because you could have something like

```
---
%run
a = 2
[step]
print(a)
---
[global]
a= 1
---
```

Executing the first cell would yield `2`. If we allow the execution of `global` section, which would effectively create a global section of 

```
a=2
a=1
```
and the result of the cell would be `1`.

**Comment by gaow** [comment]
Yes, this is why I did not propose anything yet. I'm inclined to make them read-only: anything in global section will not be mutable unless inside steps. This would be a restriction specific to SoS notebook for statements outside steps.

**Comment by BoPeng** [comment]
Readonly is very expensive to check so I have implemented something like `CAP` variables are readonly but check only if something is defined in sos ocnfig file. Actually, implementation wise it is way easier to simply prepend global sections to local cell regardless where the global section is defined. This will at least allow local definition to overwrite global definitions.

**Comment by gaow** [comment]
I'm fine with that too -- users just have to use more caution there. It is still better than, at least for me, to have to repeatedly comment out / add back `[global]` keyword to make variables usable everywhere.

**Comment by BoPeng** [comment]
ok, now `%run` executes global definitions, as documented [here](https://vatlab.github.io/SoS/doc/documentation/SoS_Magics.html#%run-1010). I also documented the tricky case for **local global sections** [here](https://vatlab.github.io/SoS/doc/documentation/SoS_Magics.html#%sosrun-1012).

In any case, I am happy that we have someway to define variables in `[global]` sections so that they can be executed by both `%run` and `%sosrun`. This is certainly a more elegant and easier way for a similar problem I had with #689.
