### ISSUE TITLE
`report` action output type should support `path`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#864]
Currently I have to use

```
report: output = _output.name
...
```

rather than

```
report: output = _output
```

due to this line:

https://github.com/vatlab/SoS/blob/master/src/sos/actions.py#L828

Perhaps `file_target` objects should also be allowed here?

**Comment by BoPeng** [comment]
Yes, you are right, `path`, `file_target`, even `paths` and `sos_targets` should be allowed here. I was looking for a general solution (e.g. handling such things at the `action` level), found it troublesome (because individual action might check type of `output` etc), but failed to handle these types in all actions that accept such parameters.
