### ISSUE TITLE
request support for rdkit

### ISSUE THREAD

**Issue by amorgat** [vatlab/SoS#876]
Hi, I installed rdkit (http://www.rdkit.org/) without apparent issue
```
> conda create -c rdkit -n my-rdkit-env rdkit
> conda activate my-rdkit-env
```

Unfortunately, when I'm trying to use this library in a sos notebook, I get a `ModuleNotFoundError` exception

```
In[1]: from rdkit import Chem
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3a181df69616> in <module>()
----> 1 from rdkit import Chem

ModuleNotFoundError: No module named 'rdkit'
```

I'm stuck with this config issue... Thanks for your support

**Comment by BoPeng** [comment]
On my mac, running

```
conda create -c rdkit -n my-rdkit-env rdkit
```
creates a rdkit environment. The second command should be

```
source activate my-rdkit-env
```
Then,
```
$ python -c 'from rdkit import Chem'
Segmentation fault: 11
```
Suppose this module works on your platform, you would need to **install jupyter notebook inside your virtual env**, otherwise jupyter will not be able to find the module in your virtual env. Then I suppose that you will also need to make sure that the `sos` kernel is installed properly for the virtual env (`jupyter kernelspec list` will show the path). Since `pip install` does not seem to install `sos` kernel properly, you would need to clone the sos-notebook repository and run `python setup.py install` to do it. (This is something I will try to address soon).

**Comment by BoPeng** [comment]
With the latest version of `sos-notebook`, you can (and need to run)

```
% python -m sos_notebook.install
```
to install `sos` kernel to the current python interpreter, which in your case should be the python in virtual env.

**Comment by BoPeng** [comment]
I suppose this has been fixed. Please re-open the ticket if this is not the case.
