### ISSUE TITLE
conda cloud for sos?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#896]
Something like

```
conda install -c bpeng sos sos-notebook ...
```
This has been proven to be useful for my Python modules with a lot of C code so that conda can compile the modules under different systems and provide binary distributions. SoS is pure Python and pip appears to be good enough.

One slight advantage of conda cloud is that it provides download count etc.

**Comment by gaow** [comment]
I would vote against conda cloud for reasons you've discussed ... unless download count etc is valued, and release to conda cloud is as easy as to pypi.

**Comment by BoPeng** [comment]
Even if conda cloud provides download count (pip no longer provides), the count reflects only downloads from conda, not from pip, which would be a (small) fraction of downloads.

SoS does have a small problem with binary distribution because our new hash library needs to be compiled from source on some system, thus require a c compiler. This is not quite related to SoS though.

**Comment by jdblischak** [comment]
> SoS does have a small problem with binary distribution because our new hash library needs to be compiled from source on some system, thus require a c compiler.

Building a conda package for SoS would solve this problem. Both xxhash and its Python API are available on the conda-forge channel. If SoS was avaiable as a conda package, then conda users could install it with `conda install -c conda-forge sos` without needing any compilers installed on their local machine.

https://anaconda.org/conda-forge/xxhash
https://anaconda.org/conda-forge/python-xxhash

**Comment by gaow** [comment]
Thanks @jdblischak for your input. Now that #1096 has been resolved, do you think it is possible you contribute to getting SoS on conda-forge? The only complication might be that `pysam` dependency that lives in other channels. But I think conda-forge is a better fit ... what's your take on this? Thanks a lot!

**Comment by jdblischak** [comment]
> The only complication might be that pysam dependency that lives in other channels. But I think conda-forge is a better fit ... what's your take on this? Thanks a lot!

@gaow Summarizing what we had discussed in Slack: I think the generic parts of sos (workflow engine and notebook) should be in conda-forge. Then sos-bioinfo can be added to bioconda since it depends on pysam (and presumably sos users that need sos-bioinfo will also want to install other bioconda packages). And since [bioconda relies on packages from conda-forge](https://bioconda.github.io/#set-up-channels), a bioconda user that runs `conda install sos-bioinfo` will seamlessly get all the generic sos components installed (assuming they've configured their conda channels correctly, but that is not an sos-specific issue). And another benefit of using conda-forge is that these packages will also be built for Windows.

**Comment by BoPeng** [comment]
@jdblischak @gaow 

I just released version 0.18.0 (some with only version number change) of `sos-bash`, `sos-javascript`, `sos-julia`, `sos-matlab`, `sos-python`, `sos-r`, `sos-ruby`, `sos-sas`, and `sos-stata`, which should work with the recently released `sos-notebook` version 0.18.2. I think it is time for us to release all of them to conda-forge. Do you have time for this?

The rest of the packages
* `sos-rq` is experimental but can get in for completeness
* `sos-scala` is not ready
* `sos-bioinfo` only supports preview of two bioinformatic formats, and we can deal with bioconda later.

**Comment by gaow** [comment]
I'm not immediately familiar with how to do it but I assume I can try one and get help from @jdblischak or find some detailed tutorials. Once one is setup the others should just follow. I should have some time this weekend for it.

**Comment by BoPeng** [comment]
I think you can copy almost everything from https://github.com/jdblischak/sos-feedstock but add the notebook stuff.

**Comment by jdblischak** [comment]
It's not a problem for me to submit these to conda-forge.

@BoPeng How do you want to handle the installation of the languages themselves? In other words, should `sos-r` have a run time requirement of `r-base`? Anaconda Cloud also has JavaScript, Julia, and Ruby. The advantage is that the required dependency is always automatically installed. The disadvantage is that this forces the end user to use the conda version.

**Comment by BoPeng** [comment]
This is indeed a problem because even in the conda environment there are `r` from channel `r` and `conda-forge` (AFAIR). They do not always work and mixing packages from both channels will lead to more trouble, and this is why I have switched back to standalone installation of R.

However, in the spirit of conda, I think we should assume that upstream packages work and include them in our recipes. In a clean environment this setup should work and it is not our problem that the environment stops working due to problems with conda or upstream packages.

**Comment by gaow** [comment]
Thanks @jdblischak it would be great if you could submit the packages! 

@BoPeng are you suggesting `sos-r` should depend on `r-base` , and similarly for other languages? What about relevant kernels and language specific configurations, eg, [as listed here](https://vatlab.github.io/sos-docs/running.html#Local-installation)?

"The disadvantage is that this forces the end user to use the conda version." I think it is a big limitation. Say I have a perfectly working Jupyter R setup but conda installation of `sos-r` will likely break it. Even more confusing is that the behavior is inconsistent with `pip install sos-r`, for example ...

Is there a smarter way out? I think the default dependency should be the same as that in pypi. But how can we cope with the additionally level of dependencies? For example in `apt-get` there is a `--no-install-recommends` (recommendations not dependencies!) switch. Only in our case the default should be no-recommands. In conda there is only this one layer of `deps` (`--no-deps`, `--only-deps`).

**Comment by BoPeng** [comment]
My point was that `conda install sos-r` is meant to provide a complete environment and should (almost) just work. If it does not work due to upstream problem, it is not our fault. If user prefers a standalone r, they can use `pip install sos-r` instead.

**Comment by jdblischak** [comment]
> it is the responsibility of r-irkernel. If the kernel does not work, it will not work with sos.

@BoPeng I don't think I follow. Are you disagreeing with something I said above? I said that the conda package `r-irkernel` will register itself automatically, but that if the user installs `sos-r` with `pip` then they will have to manually register the kernel.

**Comment by jdblischak** [comment]
> Sorry, I thought that you meant sos-r will have to install irkernel. Obviously we do not need to do that if r-irkernel does it already.

Oh, I see. Yes, I was just listing all the steps detailed in the [sos-r installation instructions](https://vatlab.github.io/sos-docs/running.html#r).

At first I thought we would only need to list `r-base` as a dependency for `sos-r`. This didn't really seem worth it to me since it can be installed in one command. However, there are actually multiple steps that need to be taken, which to me makes it more worth it to require the conda version of R for use with the conda version of sos-r.

**Comment by BoPeng** [comment]
Yes, it would be good if `sos-r` `sos-javascript` etc could work out of box since right now installation of individual kernels and required packages are still major obstacles for using sos notebook.

**Comment by jdblischak** [comment]
@BoPeng How important is the ImageMagick dependency (via Wand)? conda-forge has only built ImageMagick for Linux and macOS, so requiring this would mean that sos-notebook from conda-forge could not be installed on Windows.

https://anaconda.org/conda-forge/imagemagick
https://github.com/conda-forge/staged-recipes/pull/3515#issuecomment-322809191

**Comment by BoPeng** [comment]
I think we discussed this before and chose not to include them with `sos`, so I would ignore them and add them to `sos` when time is right.

**Comment by jdblischak** [comment]
> I think we discussed this before and chose not to include them with sos, so I would ignore them and add them to sos when time is right.

@BoPeng Correct, we discussed this specifically for SoS in https://github.com/conda-forge/sos-feedstock/pull/1#issuecomment-445105383. We were able to avoid installing ImageMagick for SoS because those dependencies are in `extras_require`: https://github.com/vatlab/SoS/blob/master/setup.py#L210

However, for sos-notebook, it lists the package Wand (an interface to the ImageMagick API) in the main requirements:

https://github.com/vatlab/sos-notebook/blob/master/setup.py#L91
https://github.com/vatlab/sos-notebook/blob/master/.travis.yml#L34

Can I remove Wand from the list of requirements for sos-notebook? In other words, does sos-notebook have error handling to fail gracefully if the Wand package is not available?

**Comment by BoPeng** [comment]
travis has it for testing but `wand` should not be included. It was included for the preview feature that has been moved to the `sos` core.

I have removed `wand` and `matplotlib` (because it is also not used directly) and released sos notebook 0.18.3.
