### ISSUE TITLE
Identical tasks cause clashes

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#920]
Here is a MWE:

```
[1]
input: '1.txt', '1.txt', group_by = 1, concurrent = True
output: [x + '.out' for x in _input]
bash: expand = True
  touch {_output}
```

So there are two tasks involved and they are identical -- meaning that they are exactly the same in all aspects. The above workflow ends in an infinite loop. 

A related point is, that is there any way we can obtain only the unique tasks before sending to build DAG and run?

**Comment by BoPeng** [comment]
In my case,

```
$ sos run test
INFO: Executing default_1:
INFO: input:   [file_target('1.txt'), file_target('1.txt')]
INFO: Waiting on another process for step default_1
INFO: Executing default_1:
INFO: input:   [file_target('1.txt'), file_target('1.txt')]
INFO: default_1 (index=0) is ignored due to saved signature
INFO: default_1 (index=1) is ignored due to saved signature
INFO: output:   [file_target('/Users/bpeng1/sos/test/1.txt.out')]
INFO: Workflow default (ID=4b8fb2aeabc666c5) is executed successfully.
```
It seems that one input group is running, another one executed successfully, and the step is executed again with saved signature.

**Comment by BoPeng** [comment]
Fixed by recent changes to internal handling of targets.

Note that the internal targets of sos was a mess because we had files (`str`), targets (`BaseTarget`, `file_target` etc) and `Undetermined` (for missing). New features were added and the logics became more and more complex. Recent patches consolidated the logics and use `sos_targets` everywhere, which should make the core more robust.
