### ISSUE TITLE
Path expand bug and signature issues

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#923]
Here is an MWE:

```
[global]
cwd = path('~/tmp')
wasp_dir = f'{cwd:a}/jnbinder-master'

[default: provides = f"{wasp_dir}/README.md"]
output: f"{wasp_dir}/README.md"
download: decompress = True, dest_file = f'{cwd:a}/WASP.zip'
    https://github.com/vatlab/jnbinder/archive/master.zip
bash: expand = True
    rm -f {cwd}/WASP.zip
```

Running this script multiple times will fully execute the workflow even though the output does exist:

```
$ sos run test.sos 
INFO: Executing default_0: 
INFO: input:   []
WASP.zip
INFO: output:   [file_target('//home/gaow/tmp/jnbinder-master/README.md')]                                     
INFO: Workflow default (ID=cfd8a518d023dd40) is executed successfully.
$ sos run test.sos 
INFO: Executing default_0: 
INFO: input:   []
WASP.zip
INFO: output:   [file_target('//home/gaow/tmp/jnbinder-master/README.md')]                                     
INFO: Workflow default (ID=cfd8a518d023dd40) is executed successfully.
```

However when I replace `cwd = path('~/tmp')` with `cwd = path('/home/gaow/tmp')` I get this at the 2nd run:

```
$ sos run test.sos 
INFO: Executing default_0: 
INFO: input:   []
INFO: default_0 (index=0) is ignored due to saved signature
INFO: output:   [file_target('/home/gaow/tmp/jnbinder-master/README.md')]
INFO: Workflow default (ID=de6478e2d9728cca) is executed successfully.
```

that is, the existing file is properly skipped. Note that for the first case the file target starts with `//home/gaow` (double `//`). I guess this is what caused the trouble.

I'm just showing one example here but actually this bug impacts many of my existing workflows -- they now no longer automatically skip completed steps.

**Comment by BoPeng** [comment]
`-v4` shows

```
DEBUG: Signature mismatch: Context variable cwd value mismatch:
 path('/Users/bpeng1/tmp') saved, path('//Users/bpeng1/tmp') current
```
so it looks like there is something wrong with `{cwd:a}`, which yields `//Users/bpeng1/tmp/jnbinder-master` before it is normalized to be saved.

**Comment by BoPeng** [comment]
This has been fixed. Note that we now automatically expand `path` so `:a` or `:u` is no longer needed (#915) and your script would be written as

```
[global]
cwd = path('~/tmp')
wasp_dir = cwd / 'jnbinder-master'

[default: provides = wasp_dir / 'README.md']
output: wasp_dir / 'README.md'
download: decompress = True, dest_file = cwd / 'WASP.zip'
    https://github.com/vatlab/jnbinder/archive/master.zip
bash: expand = True
    rm -f {cwd}/WASP.zip
``` 

to make use of the `/` syntax of `pathlib.Path`.

**Comment by gaow** [comment]
Great, this is so much more convenient. Welcome back :)

**Comment by gaow** [comment]
> Note that we now automatically expand path so :a or :u is no longer needed 

We might have to see if there are any unwanted side-effect about this ... At least for example users might want to document in their log-file the path of some files, yet wanted to keep it relative paths -- then can `str(cwd)` or something else gives me `~/tmp`?

**Comment by BoPeng** [comment]
The reason behind #915 is that we automatically expand `~`, even `*` in places such as `input: '~/a.txt'`, `output: '~/tmp'`, and because I have to use many `:u` for parameters in my scripts in case users provide a path with `~`.

I understand your concern and I actually tried to keep `str()` as `~/tmp` but it is much more difficult than I expected (`pathlib.Path` is not a traditional class with overridable `__init__`). I am therefore thinking of a `U` flag to fold username to `~`.

**Comment by gaow** [comment]
>  I am therefore thinking of a U flag to fold username to ~.

This will certainly equally work!

**Comment by BoPeng** [comment]
There can also be a `relative` flag to convert paths to shorter paths that are relative to `pwd` (opposite to `abspath` or `realpath`). This is difficult to do since `pwd` can change from step to step (option `workdir`) so it might make sense to relative to current project directory. We could even combine `U` and this option to something like `c` (compress) to convert paths to `~/.sos/...` and `relative/to/proj`.
