### ISSUE TITLE
Task options vs action options

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#958]
I've got some best practice questions that I'd like to clarify, starting from this one: what is the difference between 

```
task: expand=True
run: ...
````

and 

```
task:
run: expand = True
```

and which one is preferred?

**Comment by gaow** [comment]
And the same goes for `workdir` under `task` vs under `action` level.

**Comment by BoPeng** [comment]
I do not think we have `expand` option for task (see a list [here](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html#Task-options-17))

`workdir` can be nested so

```
task: workdir='..':
run: workdir='..'
```
will `run` at `../..` but you can use absolute paths. Both options exist because a task can contain multiple actions and regular python statements.

`env` for actions were added recently. The logic is the same (`env` at the task never can be overridden by `env` at the action level).

I would generally recommend the use of action level options because it would be easier to add/remove `task` to debug the code locally and change it to task. In this sense, perhaps we should remove these task options.

**Comment by gaow** [comment]
> I do not think we have expand option for task

Good to know ... then [that page](https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html) needs an update, if you search for `expand=True` you'll see some of them are in `task`.

> workdir can be nested

A behavior that makes good sense to me and I can imagine it be useful sometimes; but might be confusing to less experienced people. 

> I would generally recommend the use of action level options because it would be easier to add/remove task to debug the code locally and change it to task

Yes I think we should remove task options that are equivalent.

**Comment by BoPeng** [comment]
https://vatlab.github.io/sos-docs/doc/documentation/Remote_Execution.html is fixed. Thank you for reporting the problem.
