### ISSUE TITLE
Dockerized SoS workflow conflict with R system variables when `$HOME` has to be mounted

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#978]
Okay the story is that my boss just sent me an upsetting message running one of my sos-based docker image. It complains that some R packages are not found -- which my docker image certainly has anyways. Apparently, it was caused by his own `~/.R/Renviron` setting in conflict with my docker's setting. 

The reason I had to mount `$HOME:$HOME` is because SoS has to access `~/.sos` . But you can imaging having to mount `$HOME` to docker just for `~/.sos` will cause many issues. Is there a way to let it point to elsewhere? The cleanest is perhaps to use some bash `env`, if you do not want to add an option? eg.

```
SOS_GLOBAL_DIR=`pwd`/.sos
```

to set it to `./sos` for example. Default to `~/.sos` of course. That way, I can build this `ENV` to my docker file.

**Comment by gaow** [comment]
I guess another lesson learned here is to avoid sharing `$HOME` with docker image when possible ...

**Comment by BoPeng** [comment]
So the `.R` directory of his home directory got included in docker and affected R inside?

**Comment by gaow** [comment]
I cannot reproduce his error, but from the error message it suggests so, and it is the only possible explanation, because this pipeline has been successfully ran by other people who uses mac laptop and mounted `$HOME:$HOME`.

**Comment by BoPeng** [comment]
Can you run your R in docker without ~/.R?

**Comment by gaow** [comment]
I am looking for ways to do that now, but I guess it is a separate discussion right? Unload my `~/.R` might solve the problem and I'm going to have him try that once I find a way to do it in my docker image. Here I'm just raising a discussion of possible benefits to allow resetting `~/.sos`. Or the code change involved is messy?

**Comment by BoPeng** [comment]
We mount many directories by default to create more or less "native" feeling for docker images. You are running things in docker and does not want `~` but in many cases we use docker to process local files, in which case `pwd` even `~` will be needed. We could mount only user-specified volumes but not sure if that is the right thing to do.

Not sure how other workflow engines handles this.

**Comment by BoPeng** [comment]
Note that the docker image can have its own user and therefore its own HOME that is not shared with the host, which provides more separation. In this regard even our default user is arguable.

**Comment by BoPeng** [comment]
How about we make `home` etc default parameters of `volumes` so that users can override them with `--volumes`? Current implementation adds `--volumes` to sos defaults so `home` etc are always mounted.

**Comment by BoPeng** [comment]
implemented in https://github.com/vatlab/SoS/commit/cb913e85ff3eb8f7b13b6e773141f8dea56f09a8

@gaow I have revamped https://vatlab.github.io/sos-docs/doc/tutorials/SoS_Docker_Guide.html to show details the basic usage and advanced options for docker. I have completed the `docker_workdir` (new) and `volumes` section. Can I leave the `uid` section to you since you have linux and can give examples? Basically, I would like to have cases

1. default using host uid/gid.
2. using system default uid/gid, host $HOME would not be affected, It would be good to find a case that the image require the default user to run. (`--user None`)

These would be the essentials, we can add sections for other parameters later.

**Comment by BoPeng** [comment]
The newest update has stopped sharing `/home` (or `/users`) by default and makes current working directory the only directory that will always be shared (subject to `workdir`). The meaning of `volumes` is therefore clearer as it will be the additional shared directory. I think this will make the behavior more predictable but I am not sure how it will affect your use of `sos` inside of docker. My understanding is that sos can write to `~/.sos` inside of the docker so it is ok not to share `$HOME`.

**Comment by gaow** [comment]
Great! Sure i'll complete the documentation adding in what I've learned working with docker images in / wrapping SoS -- upgrade, see if things break, report or document. Sorry I'm still trying to wrap up my current undertaking today ... I'll get back to this and the other issue tomorrow.

**Comment by BoPeng** [comment]
Thanks for all the bug reports, which were certainly helpful during the determination of a better docker interface. I have tried to document the parameters in the tutorial, hopefully they make sense and are intuitive for the majority of the cases.

**Comment by gaow** [comment]
I'll work on this later this afternoon. I want to get to the point that not only the `docker_image` action inside SoS works, but also people can pull a docker image that has SoS Notebook properly installed, open it, and do interactive analysis with the software packages shipped with that docker. I was not able to do it previously due to SoS Notebook docker issues.

**Comment by BoPeng** [comment]
Right now all the work was on `docker_image` and related options. The latter sounds like our live server and I am not aware of any problem with it.

**Comment by ChrisWakefield** [comment]
What @gaow is describing sounds like "Docker in docker", that has been trouble for years.  The workaround to allow this is to mount the host machine's Docker socket in the container.  See https://getintodevops.com/blog/the-simple-way-to-run-docker-in-docker-for-ci or https://www.develves.net/blogs/asd/2016-05-27-alternative-to-docker-in-docker/
Both say to include "-v /var/run/docker.sock:/var/run/docker.sock" in your docker run command.
I don't know how to accomplish the same in Docker for Windows.

Otherwise your "docker_image" action may work fine if SoS is installed locally, but fail if using a SoS docker image.

**Comment by BoPeng** [comment]
I think Gao had a different problem. That is to say, his docker image with sos/sos-notebook and all required software fail to run because he had to share his `$HOME` to the docker image which caused problems with R inside the image. The image should have been started manually, not from sos.

The central problem is therefore if the docker image can be executed without host-mounted `HOME`. I think there is no such need because the image will have its own `~/.sos`, but obviously Gao noticed problems with `~/.sos` inside docker.

**Comment by gaow** [comment]
Thanks @ChrisWakefield yes I was not dealing with docker in docker yet. I currently mostly deal with 

1. docker of SoS to be started manually
2. using containers inside SoS

In this ticket @BoPeng has prevented potential issues in 2 by not mounting `$HOME` by default. I had no problem with this, except I'll have to change a couple of my existing workflow scripts to use `volumes` for action `docker_image`. For 1 yes I had to mount `$HOME`, or better, `$HOME/.sos` explicitly when running docker, because otherwise there is problem.

Sorry for weigh in late but I think these issues are clarified and ironed out.
