### ISSUE TITLE
Output -h message in workflow report and/or HTML export (with option)?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#985]
This is helpful for readers to understand how to run the included script.

**Comment by gaow** [comment]
I'm not sure about it. It is only useful when all parameters and steps are properly annotated, which we do not reinforce. Take the `development/release` script for example -- I do not see its `-h` to be very informative as is.

**Comment by gaow** [comment]
I agree `-h` is useful and should be the first command to run when given a new script. And it can be extremely useful for certain (simple logic) workflows, particularly a workflow that simply consolidates various scattered scripts.

I'm just not sure if we include it in workflow report. A workflow report is something generated after a successful workflow execution, and as you said if a user runs:

```
sos run script_name some_workflow -p out.html
```

then including output of  `sos run script_name -h` in `out.html` can be confusing because there is more information than that for `some_workflow` alone -- it displays all workflows.

For exported HTML file, I think it is already quite clear to see the gray background step names to know what are included. `-h`, in my view, does not offer much more than that. I guess my other issue with `-h` is that it does not (and perhaps cannot) reflect 100% the execution logic (eg, step or file target dependencies). For example for SoS manuscript example, outcome of `sos run Outcome_Oriented.sos -h` and `sos run Mixed_Style.sos -h` are in fact even a bit confusing, opposite from telling me how the script should be properly executed.

**Comment by BoPeng** [comment]
How about adding at the footer something like "use sos run script -h" for usage?

**Comment by gaow** [comment]
I think that's good enough, and can go the header table for workflow exported HTML.

**Comment by gaow** [comment]
BTW there is a minor issue with shared workflow steps:

```
[a,b]
print(999)
```

then `sos run test.sos -h` you'll see under `Sections` only `a` is displayed (sorry cannot copy-paste here due to some mac weirdness but i do not want to reboot the laptop now).

**Comment by BoPeng** [comment]
It works as expected here

```
$ sos run test -h
usage: sos run test [workflow_name | -t targets] [options] [workflow_options]
  workflow_name:        Single or combined workflows defined in this script
  targets:              One or more targets to generate
  options:              Single-hyphen sos parameters (see "sos run -h" for details)
  workflow_options:     Double-hyphen workflow-specific parameters

Workflows:
  a
  b

Sections
  a:
```

**Comment by gaow** [comment]
But in `Sections` there is only information for `a`, not `b`, right?

**Comment by BoPeng** [comment]
I see, you talk about sections..., not workflows.

**Comment by BoPeng** [comment]
New footer

![image](https://user-images.githubusercontent.com/9889312/41577973-7a7bfa2a-7355-11e8-99c2-c9876eff471f.png)

No need to add to report because the report has command for how the report is generated, which provides some usage info.
